// GENERATED by tests/protocol/gen_state_rust.py from
// tests/protocol/state_machine.json — do not edit by hand.

/// 1:1 mirror of the JSON transition table (drift detection).
pub fn expected(state: &str, event: &str) -> Option<&'static str> {
    Some(match (state, event) {
        ("DISCOVERING", "DISCOVERY_FOUND") => "PAIRING",
        ("DISCOVERING", "FATAL_ERROR") => "FAILED",
        ("PAIRING", "FATAL_ERROR") => "FAILED",
        ("PAIRING", "PAIR_ABORT") => "DISCOVERING",
        ("PAIRING", "PAIR_ACCEPTED") => "CONNECTING",
        ("PAIRING", "PAIR_INVALID") => "FAILED",
        ("CONNECTING", "ATTEMPTS_EXHAUSTED") => "FAILED",
        ("CONNECTING", "FATAL_ERROR") => "FAILED",
        ("CONNECTING", "LINK_ESTABLISHED") => "AUTHENTICATING",
        ("CONNECTING", "LINK_FAILED") => "RECONNECTING",
        ("CONNECTING", "STOP_REQUESTED") => "CLOSING",
        ("AUTHENTICATING", "ATTEMPTS_EXHAUSTED") => "FAILED",
        ("AUTHENTICATING", "FATAL_ERROR") => "FAILED",
        ("AUTHENTICATING", "HANDSHAKE_OK") => "NEGOTIATING",
        ("AUTHENTICATING", "LINK_FAILED") => "RECONNECTING",
        ("NEGOTIATING", "ATTEMPTS_EXHAUSTED") => "FAILED",
        ("NEGOTIATING", "FATAL_ERROR") => "FAILED",
        ("NEGOTIATING", "NEGOTIATION_FAILED") => "RECONNECTING",
        ("NEGOTIATING", "NEGOTIATION_OK") => "CONNECTED",
        ("CONNECTED", "FATAL_ERROR") => "FAILED",
        ("CONNECTED", "HEALTH_DEGRADED") => "DEGRADED",
        ("CONNECTED", "LINK_LOST") => "RECONNECTING",
        ("CONNECTED", "STOP_REQUESTED") => "CLOSING",
        ("DEGRADED", "FATAL_ERROR") => "FAILED",
        ("DEGRADED", "HEALTH_RECOVERED") => "CONNECTED",
        ("DEGRADED", "HEALTH_TIMEOUT") => "RECONNECTING",
        ("DEGRADED", "LINK_LOST") => "RECONNECTING",
        ("DEGRADED", "STOP_REQUESTED") => "CLOSING",
        ("RECONNECTING", "ATTEMPTS_EXHAUSTED") => "FAILED",
        ("RECONNECTING", "FATAL_ERROR") => "FAILED",
        ("RECONNECTING", "RESUME_READY") => "CONNECTING",
        ("RECONNECTING", "STOP_REQUESTED") => "CLOSING",
        ("CLOSING", "CLOSE_CONFIRMED") => "CLOSED",
        ("CLOSING", "CLOSE_TIMEOUT") => "CLOSED",
        ("CLOSING", "FATAL_ERROR") => "FAILED",
        ("CLOSED", "NEW_SESSION") => "DISCOVERING",
        ("FAILED", "RESET") => "CLOSED",
        _ => return None,
    })
}

pub fn transition_count() -> usize { 37 }
