#!/usr/bin/env python3
"""Generate host/crates/protocol/src/state_gen.rs from state_machine.json.

Run in CI before `cargo test` (and locally after editing the JSON).
The generated module is a 1:1 code mirror of the JSON table; Rust unit
tests compare it against the hand-written `state.rs` table.
"""
import json
import os

ROOT = os.path.join(os.path.dirname(__file__), "..", "..")
SPEC = json.load(open(os.path.join(ROOT, "tests", "protocol", "state_machine.json")))
OUT = os.path.join(ROOT, "host/crates/protocol/src/state_gen.rs")

lines = [
    "// GENERATED by tests/protocol/gen_state_rust.py from",
    "// tests/protocol/state_machine.json — do not edit by hand.",
    "",
    "/// 1:1 mirror of the JSON transition table (drift detection).",
    "pub fn expected(state: &str, event: &str) -> Option<&'static str> {",
    "    use std::collections::hash_map::DefaultHasher;",
    "    Some(match (state, event) {",
]
count = 0
for state, table in SPEC["transitions"].items():
    for ev, nxt in sorted(table.items()):
        lines.append(
            f'        ("{state}", "{ev}") => "{nxt}",')
        count += 1
lines += [
    "        _ => return None,",
    "    })",
    "}",
    "",
    f"pub fn transition_count() -> usize {{ {count} }}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"generated {os.path.relpath(OUT)} ({count} transitions)")
